CREATE TABLE IF NOT EXISTS DataType (
    DataTypeID INTEGER PRIMARY KEY AUTOINCREMENT,
    DataTypeName TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS ShapeType (
    ShapeTypeID INTEGER PRIMARY KEY AUTOINCREMENT,
    TypeName TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS ImageCategory (
    ImageCategoryID INTEGER PRIMARY KEY AUTOINCREMENT,
    CategoryName TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS AssetCategory (
    AssetCategoryID INTEGER PRIMARY KEY AUTOINCREMENT,
    CategoryNumber INTEGER NOT NULL UNIQUE,
    CategoryName TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Asset (
    AssetID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetName TEXT NOT NULL,
    AssetNumber INTEGER NOT NULL,
    AssetVariant TEXT,
    AssetDescription TEXT,
    AssetCategoryID INTEGER NOT NULL,
    FOREIGN KEY (AssetCategoryID) REFERENCES AssetCategory (AssetCategoryID)
);
CREATE TABLE IF NOT EXISTS AssetAttribute (
    AssetAttributeID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetID INTEGER NOT NULL,
    AttributeOrderNumber INTEGER NOT NULL,
    AttributeName TEXT NOT NULL,
    DataTypeID INTEGER NOT NULL,
    AttributeRemark TEXT,
    FOREIGN KEY (DataTypeID) REFERENCES DataType (DataTypeID) ON DELETE CASCADE,
    FOREIGN KEY (AssetID) REFERENCES Asset (AssetID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS AssetShape (
    AssetShapeID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetID INTEGER NOT NULL,
    ShapeTypeID INTEGER NOT NULL,
    ShapeDescription TEXT,
    FOREIGN KEY (ShapeTypeID) REFERENCES ShapeType (ShapeTypeID),
    FOREIGN KEY (AssetID) REFERENCES Asset (AssetID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS AssetImage (
    AssetImageID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetID INTEGER NOT NULL,
    ImageFileName TEXT NOT NULL,
    ImageCategoryID INTEGER NOT NULL,
    FOREIGN KEY (ImageCategoryID) REFERENCES ImageCategory (ImageCategoryID),
    FOREIGN KEY (AssetID) REFERENCES Asset (AssetID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS AssetImportList (
    AssetImportListID INTEGER PRIMARY KEY AUTOINCREMENT,
    AssetID INTEGER NOT NULL,
    ImportlistHeader TEXT NOT NULL,
    Importlist_2ndRow TEXT NOT NULL,
    Importlist_3ndRow TEXT NOT NULL,
    FOREIGN KEY (AssetID) REFERENCES Asset (AssetID) ON DELETE CASCADE
);
CREATE TABLE Project (
    ProjectID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProjectName TEXT NOT NULL,
    PathMedia TEXT NOT NULL
);